# Use an official Python image
FROM python:3.9-slim


# Set working directory
WORKDIR /app


# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


# Install auto-instrumentation packages (based on installed libs like Flask, SQLAlchemy)
RUN opentelemetry-bootstrap -a install


# Copy the rest of the application code
COPY . .


# Expose the Flask app's port
EXPOSE 3002


CMD ["opentelemetry-instrument","--traces_exporter=console,otlp","--metrics_exporter=console","--exporter_otlp_protocol=http/protobuf","--service_name=student-reg","--exporter_otlp_endpoint=http://otel-collector:4318","python","app.py"]